# Generated by Django 4.2.7 on 2025-08-13 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('type', models.CharField(choices=[('income', 'Receita'), ('expense', 'Despesa')], max_length=10, verbose_name='Tipo de Transação')),
                ('color', models.CharField(default='#FFD700', help_text='Cor em formato hexadecimal (ex: #FFD700)', max_length=7, verbose_name='Cor')),
                ('icon', models.CharField(blank=True, help_text='Emoji ou ícone para representar a categoria', max_length=50, null=True, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['type', 'name'],
                'unique_together': {('user', 'name', 'type')},
            },
        ),
    ]
