# Generated by Django 4.2.7 on 2025-08-13 19:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('emergency', 'Reserva de Emergência'), ('vacation', 'Viagem/Férias'), ('house', 'Casa/Imóvel'), ('car', 'Veículo'), ('education', 'Educação'), ('investment', 'Investimento'), ('debt', 'Quitação de Dívida'), ('other', 'Outro')], max_length=20, verbose_name='Categoria')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor Objetivo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Atual')),
                ('target_date', models.DateField(verbose_name='Data Objetivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('completed', 'Concluída'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='active', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridade')),
                ('is_public', models.BooleanField(default=False, verbose_name='Meta Pública')),
                ('auto_save', models.BooleanField(default=False, verbose_name='Economia Automática')),
                ('monthly_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Contribuição Mensal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='goals_goal_user_id_7ad9fc_idx'), models.Index(fields=['user', 'target_date'], name='goals_goal_user_id_9d8fa4_idx'), models.Index(fields=['user', 'priority'], name='goals_goal_user_id_1dfc65_idx')],
            },
        ),
    ]
